### ISSUE TITLE
External Receiver is Used

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#11]
The detector should highlight all the external receivers defined within the project (see: `AstReceiver` node and its `selector` field).

## Context

Contracts in TON communicate with each other using messages. This model resembles the [actor model](https://en.wikipedia.org/wiki/Actor_model). The contract can `send` messages to any other contract and receive using the defined receiver functions.

Tact supports two kinds of message receiver functions: internal and external. External messages [are different](https://docs.tact-lang.org/book/external#how-external-messages-are-different) from internal messages: the contract has to pay gas for receiving messages, and there are some limits in gas processing.

Thus, the logic implemented in external messages may require extra attention from an auditor.

## Examples
```
external("Check Timeout") { // Highlighted by the detector
  acceptMessage();
}
```

**Comment by DLochmelis33** [comment]
I'd like to take this one
