### ISSUE TITLE
`send` in Loop

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#12]
The detector should highlight loop statements that use the [`send`](https://docs.tact-lang.org/book/send#send-message) function call (`AstStaticCall`) in their bodies.

## Context
The `send` operation costs gas, i.e., it uses resources defined in a contract. Loop statements containing the `send` function call might be problematic, especially if the loop condition is unbounded or depends on user input or previous interactions with the contract. This operation might drain gas from the contract, effectively making it unusable for a while.

Thus, we want to highlight these cases for an auditor to review the relevant loop conditions.

## Example
```
while (a > self.num) {
  // other statements
  send(/* ... */); // Highlighted: Using send in the loop
}
```

---

The real-world implementation should be more complicated an use inter-procedural analysis: https://github.com/nowarp/misti/issues/131. We don't need this in the assignment.

**Comment by InversionSpaces** [comment]
I want to take this one
