### ISSUE TITLE
Untyped `let` Is Used

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#13]
Highlight local variable definitions that use local type inference.

## Context
Tact supports local type inference for variables. This means the developer can write both:
```
let a: Int = 42;
let a = 42;
```

This detector should highlight untyped `let` definitions, as the explicit definition may be more readable.

## Example
```
let a = 42; // Highlighted
```

Use instead:
```
let a: Int = 42;
```

**Comment by FerrumBrain** [comment]
Taken by Timur Kudashev
