### ISSUE TITLE
`nativeRandom` Is Used

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#15]
The `nativeRandom` function calls should be highlighted.

## Context
[`nativeRandom`](https://docs.tact-lang.org/ref/core-advanced#nativerandom) is a random generation function that requires prior random generator initialization. Therefore, it is suggested to use `randomInt` instead.

**Comment by StepanovAndreyPsk** [comment]
I would like to take this issue
