### ISSUE TITLE
`if .. else if` should have `else`

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#3]
The conditional statement (`AstCondition`) that includes `else if` should always have an `else` part.

## Why is it bad?
A missing `else` statement makes the source code less readable. Therefore, it is recommended to always include it.

## Example
```
if (a > 5) { /* ... */ }
else if (a < 2) { /* ... */ }
// Bad: Missing else
```

Use instead:
```
if (a > 5) { /* ... */ }
else if (a < 2) { /* ... */ }
else { /* ... */ }
```
---
This rule is enforced by [MISRA](https://www.misra.org.uk) standards commonly used in developing safety-critical systems:
* MISRA-C-15.7
* MISRA-CPP-6.4.2

**Comment by nekitivlev** [comment]
I will take this
