### ISSUE TITLE
Definite Assignment Analysis

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#33]
Checks whether variables are guaranteed to be assigned before use. Since variables in Tact cannot be uninitialized, we assume, that the variable should be reassigned after the definition using `AstStatementAssign` or `AstStatementAugmentedAssign`.

**Direction:** Forward
**Type:** Must Analysis

**Comment by StepanovAndreyPsk** [comment]
I'll take this one
