### ISSUE TITLE
Magic Numbers

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#4]
The detector reports magic numbers used in binary operations (`AstOpBinary` expressions). The assignee can choose which pattern to report; it is suggested to report all binary operations containing numbers (`AstNumber`) on both the lhs and rhs.

## Why is it bad?
Magic numbers make code unclear and harder to maintain. Use named constants for better readability.

## Example
```
let a: Int = (1000 * 2) + 1;
```

Use instead:
```
const DEFAULT_AMOUNT: Int = 1000;
const BLOCK_REWARD_MULTIPLIER: Int = 2;
const BLOCK_CONFIRMATION_COUNT: Int = 1;

let a: Int = (DEFAULT_AMOUNT * BLOCK_REWARD_MULTIPLIER) + BLOCK_CONFIRMATION_COUNT;
```

**Comment by ozzush** [comment]
I will take this
