### ISSUE TITLE
Read-only Field

### ISSUE THREAD

**Issue by jubnzv** [Static-Homeworks-CUB/fall2024#5]
The detector highlights all contract fields that have never been assigned a different value (`self.field = <new_value>`).

## Why is it bad?
Such a field can typically be replaced with a constant.

## Example
```
contract Main {
  value: Int = 42; // Bad: The value is never changed
  function getValue(): Address { return self.value; }
}
```

Use instead:
```
const value: Int = 42; 
contract Main {
  function getValue(): Address { return value; }
}
```

---

Optional task: also check uses of the trait fields this contract implements.

**Comment by shirokov-kirill** [comment]
I'll take this one
